// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerramentiConfigurator.Data;

#nullable disable

namespace SerramentiConfigurator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514000440_InitialIndustrialSetupReal")]
    partial class InitialIndustrialSetupReal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SerramentiConfigurator.Models.AccessorioCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessoriCatalogo");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Cantiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<string>("Localita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cantieri");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitaIva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Commessa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantiereId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitoloCommessa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CantiereId");

                    b.ToTable("Commesse");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.ElementoInfisso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altezza")
                        .HasColumnType("int");

                    b.Property<int>("AltezzaSopraluce")
                        .HasColumnType("int");

                    b.Property<int>("AltezzaZoccolo")
                        .HasColumnType("int");

                    b.Property<bool>("AntaHaZoccoloInferiore")
                        .HasColumnType("bit");

                    b.Property<string>("Colore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommessaId")
                        .HasColumnType("int");

                    b.Property<string>("EtichettaVano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HaFiancoluce")
                        .HasColumnType("bit");

                    b.Property<bool>("HaSopraluce")
                        .HasColumnType("bit");

                    b.Property<int>("Larghezza")
                        .HasColumnType("int");

                    b.Property<int>("LarghezzaFiancoluce")
                        .HasColumnType("int");

                    b.Property<int>("NumeroAnte")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCerniere")
                        .HasColumnType("int");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<string>("SerieProfilo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TelaioDestro")
                        .HasColumnType("bit");

                    b.Property<bool>("TelaioInferiore")
                        .HasColumnType("bit");

                    b.Property<bool>("TelaioSinistro")
                        .HasColumnType("bit");

                    b.Property<bool>("TelaioSuperiore")
                        .HasColumnType("bit");

                    b.Property<string>("TipoAperturaFerramenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoManiglia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSoglia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVetro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipologiaApertura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersoApertura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.ToTable("ElementiInfissi");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.ProfiloCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LunghezzaCommercialeBarra")
                        .HasColumnType("float");

                    b.Property<double>("PesoAlMetro")
                        .HasColumnType("float");

                    b.Property<decimal>("PrezzoAlMetro")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SerieSerramentoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoProfilo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SerieSerramentoId");

                    b.ToTable("ProfiliCatalogo");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.RegolaFerramenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceAccessorioCorrelato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogicaCalcolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantitaMoltiplicatore")
                        .HasColumnType("int");

                    b.Property<string>("SerieProfilo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAperturaFerramenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MatriceRegole");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.SerieSerramento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodiceSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LunghezzaBarraDefault")
                        .HasColumnType("float");

                    b.Property<string>("TipoSistema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SerieSerramenti");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Cantiere", b =>
                {
                    b.HasOne("SerramentiConfigurator.Models.Cliente", null)
                        .WithMany("Cantieri")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Commessa", b =>
                {
                    b.HasOne("SerramentiConfigurator.Models.Cantiere", null)
                        .WithMany("Commesse")
                        .HasForeignKey("CantiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.ElementoInfisso", b =>
                {
                    b.HasOne("SerramentiConfigurator.Models.Commessa", null)
                        .WithMany("Elementi")
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.ProfiloCatalogo", b =>
                {
                    b.HasOne("SerramentiConfigurator.Models.SerieSerramento", null)
                        .WithMany("Profili")
                        .HasForeignKey("SerieSerramentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Cantiere", b =>
                {
                    b.Navigation("Commesse");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Cliente", b =>
                {
                    b.Navigation("Cantieri");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.Commessa", b =>
                {
                    b.Navigation("Elementi");
                });

            modelBuilder.Entity("SerramentiConfigurator.Models.SerieSerramento", b =>
                {
                    b.Navigation("Profili");
                });
#pragma warning restore 612, 618
        }
    }
}
