<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
		<!-- Core di ASP.NET 10 OpenAPI (Nativo) -->
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />

		<!-- Interfaccia grafica moderna sostitutiva di Swagger UI -->
		<PackageReference Include="Scalar.AspNetCore" Version="2.0.14" />

		<!-- Sincronizzazione ed Accesso Dati SQL Server Express -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<!-- Importazione archivi FP Pro da Access -->
		<PackageReference Include="ExcelDataReader" Version="3.8.0" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />

		<!-- Orchestrazione Blazor Hosted -->
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.7" />
		<ProjectReference Include="..\SerramentiConfigurator.Client\SerramentiConfigurator.Client.csproj" />
	</ItemGroup>

</Project>
